//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 01:31:16 PM IST 
//


package com.sereneast.orchestramdm.keysight.mdmcustom.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locale.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="locale"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="ar"/&gt;
 *     &lt;enumeration value="ar_AE"/&gt;
 *     &lt;enumeration value="ar_BH"/&gt;
 *     &lt;enumeration value="ar_DZ"/&gt;
 *     &lt;enumeration value="ar_EG"/&gt;
 *     &lt;enumeration value="ar_IQ"/&gt;
 *     &lt;enumeration value="ar_JO"/&gt;
 *     &lt;enumeration value="ar_KW"/&gt;
 *     &lt;enumeration value="ar_LB"/&gt;
 *     &lt;enumeration value="ar_LY"/&gt;
 *     &lt;enumeration value="ar_MA"/&gt;
 *     &lt;enumeration value="ar_OM"/&gt;
 *     &lt;enumeration value="ar_QA"/&gt;
 *     &lt;enumeration value="ar_SA"/&gt;
 *     &lt;enumeration value="ar_SD"/&gt;
 *     &lt;enumeration value="ar_SY"/&gt;
 *     &lt;enumeration value="ar_TN"/&gt;
 *     &lt;enumeration value="ar_YE"/&gt;
 *     &lt;enumeration value="be"/&gt;
 *     &lt;enumeration value="be_BY"/&gt;
 *     &lt;enumeration value="bg"/&gt;
 *     &lt;enumeration value="bg_BG"/&gt;
 *     &lt;enumeration value="ca"/&gt;
 *     &lt;enumeration value="ca_ES"/&gt;
 *     &lt;enumeration value="ca_ES_EURO"/&gt;
 *     &lt;enumeration value="cs"/&gt;
 *     &lt;enumeration value="cs_CZ"/&gt;
 *     &lt;enumeration value="da"/&gt;
 *     &lt;enumeration value="da_DK"/&gt;
 *     &lt;enumeration value="de"/&gt;
 *     &lt;enumeration value="de_AT"/&gt;
 *     &lt;enumeration value="de_AT_EURO"/&gt;
 *     &lt;enumeration value="de_CH"/&gt;
 *     &lt;enumeration value="de_DE"/&gt;
 *     &lt;enumeration value="de_DE_EURO"/&gt;
 *     &lt;enumeration value="de_LU"/&gt;
 *     &lt;enumeration value="de_LU_EURO"/&gt;
 *     &lt;enumeration value="el"/&gt;
 *     &lt;enumeration value="el_GR"/&gt;
 *     &lt;enumeration value="en"/&gt;
 *     &lt;enumeration value="en_AU"/&gt;
 *     &lt;enumeration value="en_BE"/&gt;
 *     &lt;enumeration value="en_BE_EURO"/&gt;
 *     &lt;enumeration value="en_CA"/&gt;
 *     &lt;enumeration value="en_GB"/&gt;
 *     &lt;enumeration value="en_IE"/&gt;
 *     &lt;enumeration value="en_IE_EURO"/&gt;
 *     &lt;enumeration value="en_NZ"/&gt;
 *     &lt;enumeration value="en_US"/&gt;
 *     &lt;enumeration value="en_ZA"/&gt;
 *     &lt;enumeration value="es"/&gt;
 *     &lt;enumeration value="es_AR"/&gt;
 *     &lt;enumeration value="es_BO"/&gt;
 *     &lt;enumeration value="es_CL"/&gt;
 *     &lt;enumeration value="es_CO"/&gt;
 *     &lt;enumeration value="es_CR"/&gt;
 *     &lt;enumeration value="es_DO"/&gt;
 *     &lt;enumeration value="es_EC"/&gt;
 *     &lt;enumeration value="es_ES"/&gt;
 *     &lt;enumeration value="es_ES_EURO"/&gt;
 *     &lt;enumeration value="es_GT"/&gt;
 *     &lt;enumeration value="es_HN"/&gt;
 *     &lt;enumeration value="en_IN"/&gt;
 *     &lt;enumeration value="es_MX"/&gt;
 *     &lt;enumeration value="es_NI"/&gt;
 *     &lt;enumeration value="es_PA"/&gt;
 *     &lt;enumeration value="es_PE"/&gt;
 *     &lt;enumeration value="es_PR"/&gt;
 *     &lt;enumeration value="es_PY"/&gt;
 *     &lt;enumeration value="es_SV"/&gt;
 *     &lt;enumeration value="es_US"/&gt;
 *     &lt;enumeration value="es_UY"/&gt;
 *     &lt;enumeration value="es_VE"/&gt;
 *     &lt;enumeration value="et"/&gt;
 *     &lt;enumeration value="et_EE"/&gt;
 *     &lt;enumeration value="fi"/&gt;
 *     &lt;enumeration value="fi_FI"/&gt;
 *     &lt;enumeration value="fi_FI_EURO"/&gt;
 *     &lt;enumeration value="fr"/&gt;
 *     &lt;enumeration value="fr_BE"/&gt;
 *     &lt;enumeration value="fr_BE_EURO"/&gt;
 *     &lt;enumeration value="fr_CA"/&gt;
 *     &lt;enumeration value="fr_CH"/&gt;
 *     &lt;enumeration value="fr_FR"/&gt;
 *     &lt;enumeration value="fr_FR_EURO"/&gt;
 *     &lt;enumeration value="fr_LU"/&gt;
 *     &lt;enumeration value="fr_LU_EURO"/&gt;
 *     &lt;enumeration value="hi_IN"/&gt;
 *     &lt;enumeration value="hr"/&gt;
 *     &lt;enumeration value="hr_HR"/&gt;
 *     &lt;enumeration value="hu"/&gt;
 *     &lt;enumeration value="hu_HU"/&gt;
 *     &lt;enumeration value="is"/&gt;
 *     &lt;enumeration value="is_IS"/&gt;
 *     &lt;enumeration value="it"/&gt;
 *     &lt;enumeration value="it_CH"/&gt;
 *     &lt;enumeration value="it_IT"/&gt;
 *     &lt;enumeration value="it_IT_EURO"/&gt;
 *     &lt;enumeration value="iw"/&gt;
 *     &lt;enumeration value="iw_IL"/&gt;
 *     &lt;enumeration value="ja"/&gt;
 *     &lt;enumeration value="ja_JP"/&gt;
 *     &lt;enumeration value="ko"/&gt;
 *     &lt;enumeration value="ko_KR"/&gt;
 *     &lt;enumeration value="lt"/&gt;
 *     &lt;enumeration value="lt_LT"/&gt;
 *     &lt;enumeration value="lv"/&gt;
 *     &lt;enumeration value="lv_LV"/&gt;
 *     &lt;enumeration value="mk"/&gt;
 *     &lt;enumeration value="mk_MK"/&gt;
 *     &lt;enumeration value="nl"/&gt;
 *     &lt;enumeration value="nl_BE"/&gt;
 *     &lt;enumeration value="nl_BE_EURO"/&gt;
 *     &lt;enumeration value="nl_NL"/&gt;
 *     &lt;enumeration value="nl_NL_EURO"/&gt;
 *     &lt;enumeration value="no"/&gt;
 *     &lt;enumeration value="no_NO"/&gt;
 *     &lt;enumeration value="no_NO_NY"/&gt;
 *     &lt;enumeration value="pl"/&gt;
 *     &lt;enumeration value="pl_PL"/&gt;
 *     &lt;enumeration value="pt"/&gt;
 *     &lt;enumeration value="pt_BR"/&gt;
 *     &lt;enumeration value="pt_PT"/&gt;
 *     &lt;enumeration value="pt_PT_EURO"/&gt;
 *     &lt;enumeration value="ro"/&gt;
 *     &lt;enumeration value="ro_RO"/&gt;
 *     &lt;enumeration value="ru"/&gt;
 *     &lt;enumeration value="ru_RU"/&gt;
 *     &lt;enumeration value="sh"/&gt;
 *     &lt;enumeration value="sh_YU"/&gt;
 *     &lt;enumeration value="sk"/&gt;
 *     &lt;enumeration value="sk_SK"/&gt;
 *     &lt;enumeration value="sl"/&gt;
 *     &lt;enumeration value="sl_SI"/&gt;
 *     &lt;enumeration value="sq"/&gt;
 *     &lt;enumeration value="sq_AL"/&gt;
 *     &lt;enumeration value="sr"/&gt;
 *     &lt;enumeration value="sr_YU"/&gt;
 *     &lt;enumeration value="sv"/&gt;
 *     &lt;enumeration value="sv_SE"/&gt;
 *     &lt;enumeration value="th"/&gt;
 *     &lt;enumeration value="th_TH"/&gt;
 *     &lt;enumeration value="th_TH_TH"/&gt;
 *     &lt;enumeration value="tr"/&gt;
 *     &lt;enumeration value="tr_TR"/&gt;
 *     &lt;enumeration value="uk"/&gt;
 *     &lt;enumeration value="uk_UA"/&gt;
 *     &lt;enumeration value="vi"/&gt;
 *     &lt;enumeration value="vi_VN"/&gt;
 *     &lt;enumeration value="zh"/&gt;
 *     &lt;enumeration value="zh_CN"/&gt;
 *     &lt;enumeration value="zh_HK"/&gt;
 *     &lt;enumeration value="zh_TW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "locale", namespace = "urn:ebx-schemas:common_1.0")
@XmlEnum
public enum Locale {

    @XmlEnumValue("ar")
    AR("ar"),
    @XmlEnumValue("ar_AE")
    AR_AE("ar_AE"),
    @XmlEnumValue("ar_BH")
    AR_BH("ar_BH"),
    @XmlEnumValue("ar_DZ")
    AR_DZ("ar_DZ"),
    @XmlEnumValue("ar_EG")
    AR_EG("ar_EG"),
    @XmlEnumValue("ar_IQ")
    AR_IQ("ar_IQ"),
    @XmlEnumValue("ar_JO")
    AR_JO("ar_JO"),
    @XmlEnumValue("ar_KW")
    AR_KW("ar_KW"),
    @XmlEnumValue("ar_LB")
    AR_LB("ar_LB"),
    @XmlEnumValue("ar_LY")
    AR_LY("ar_LY"),
    @XmlEnumValue("ar_MA")
    AR_MA("ar_MA"),
    @XmlEnumValue("ar_OM")
    AR_OM("ar_OM"),
    @XmlEnumValue("ar_QA")
    AR_QA("ar_QA"),
    @XmlEnumValue("ar_SA")
    AR_SA("ar_SA"),
    @XmlEnumValue("ar_SD")
    AR_SD("ar_SD"),
    @XmlEnumValue("ar_SY")
    AR_SY("ar_SY"),
    @XmlEnumValue("ar_TN")
    AR_TN("ar_TN"),
    @XmlEnumValue("ar_YE")
    AR_YE("ar_YE"),
    @XmlEnumValue("be")
    BE("be"),
    @XmlEnumValue("be_BY")
    BE_BY("be_BY"),
    @XmlEnumValue("bg")
    BG("bg"),
    @XmlEnumValue("bg_BG")
    BG_BG("bg_BG"),
    @XmlEnumValue("ca")
    CA("ca"),
    @XmlEnumValue("ca_ES")
    CA_ES("ca_ES"),
    @XmlEnumValue("ca_ES_EURO")
    CA_ES_EURO("ca_ES_EURO"),
    @XmlEnumValue("cs")
    CS("cs"),
    @XmlEnumValue("cs_CZ")
    CS_CZ("cs_CZ"),
    @XmlEnumValue("da")
    DA("da"),
    @XmlEnumValue("da_DK")
    DA_DK("da_DK"),
    @XmlEnumValue("de")
    DE("de"),
    @XmlEnumValue("de_AT")
    DE_AT("de_AT"),
    @XmlEnumValue("de_AT_EURO")
    DE_AT_EURO("de_AT_EURO"),
    @XmlEnumValue("de_CH")
    DE_CH("de_CH"),
    @XmlEnumValue("de_DE")
    DE_DE("de_DE"),
    @XmlEnumValue("de_DE_EURO")
    DE_DE_EURO("de_DE_EURO"),
    @XmlEnumValue("de_LU")
    DE_LU("de_LU"),
    @XmlEnumValue("de_LU_EURO")
    DE_LU_EURO("de_LU_EURO"),
    @XmlEnumValue("el")
    EL("el"),
    @XmlEnumValue("el_GR")
    EL_GR("el_GR"),
    @XmlEnumValue("en")
    EN("en"),
    @XmlEnumValue("en_AU")
    EN_AU("en_AU"),
    @XmlEnumValue("en_BE")
    EN_BE("en_BE"),
    @XmlEnumValue("en_BE_EURO")
    EN_BE_EURO("en_BE_EURO"),
    @XmlEnumValue("en_CA")
    EN_CA("en_CA"),
    @XmlEnumValue("en_GB")
    EN_GB("en_GB"),
    @XmlEnumValue("en_IE")
    EN_IE("en_IE"),
    @XmlEnumValue("en_IE_EURO")
    EN_IE_EURO("en_IE_EURO"),
    @XmlEnumValue("en_NZ")
    EN_NZ("en_NZ"),
    @XmlEnumValue("en_US")
    EN_US("en_US"),
    @XmlEnumValue("en_ZA")
    EN_ZA("en_ZA"),
    @XmlEnumValue("es")
    ES("es"),
    @XmlEnumValue("es_AR")
    ES_AR("es_AR"),
    @XmlEnumValue("es_BO")
    ES_BO("es_BO"),
    @XmlEnumValue("es_CL")
    ES_CL("es_CL"),
    @XmlEnumValue("es_CO")
    ES_CO("es_CO"),
    @XmlEnumValue("es_CR")
    ES_CR("es_CR"),
    @XmlEnumValue("es_DO")
    ES_DO("es_DO"),
    @XmlEnumValue("es_EC")
    ES_EC("es_EC"),
    @XmlEnumValue("es_ES")
    ES_ES("es_ES"),
    @XmlEnumValue("es_ES_EURO")
    ES_ES_EURO("es_ES_EURO"),
    @XmlEnumValue("es_GT")
    ES_GT("es_GT"),
    @XmlEnumValue("es_HN")
    ES_HN("es_HN"),
    @XmlEnumValue("en_IN")
    EN_IN("en_IN"),
    @XmlEnumValue("es_MX")
    ES_MX("es_MX"),
    @XmlEnumValue("es_NI")
    ES_NI("es_NI"),
    @XmlEnumValue("es_PA")
    ES_PA("es_PA"),
    @XmlEnumValue("es_PE")
    ES_PE("es_PE"),
    @XmlEnumValue("es_PR")
    ES_PR("es_PR"),
    @XmlEnumValue("es_PY")
    ES_PY("es_PY"),
    @XmlEnumValue("es_SV")
    ES_SV("es_SV"),
    @XmlEnumValue("es_US")
    ES_US("es_US"),
    @XmlEnumValue("es_UY")
    ES_UY("es_UY"),
    @XmlEnumValue("es_VE")
    ES_VE("es_VE"),
    @XmlEnumValue("et")
    ET("et"),
    @XmlEnumValue("et_EE")
    ET_EE("et_EE"),
    @XmlEnumValue("fi")
    FI("fi"),
    @XmlEnumValue("fi_FI")
    FI_FI("fi_FI"),
    @XmlEnumValue("fi_FI_EURO")
    FI_FI_EURO("fi_FI_EURO"),
    @XmlEnumValue("fr")
    FR("fr"),
    @XmlEnumValue("fr_BE")
    FR_BE("fr_BE"),
    @XmlEnumValue("fr_BE_EURO")
    FR_BE_EURO("fr_BE_EURO"),
    @XmlEnumValue("fr_CA")
    FR_CA("fr_CA"),
    @XmlEnumValue("fr_CH")
    FR_CH("fr_CH"),
    @XmlEnumValue("fr_FR")
    FR_FR("fr_FR"),
    @XmlEnumValue("fr_FR_EURO")
    FR_FR_EURO("fr_FR_EURO"),
    @XmlEnumValue("fr_LU")
    FR_LU("fr_LU"),
    @XmlEnumValue("fr_LU_EURO")
    FR_LU_EURO("fr_LU_EURO"),
    @XmlEnumValue("hi_IN")
    HI_IN("hi_IN"),
    @XmlEnumValue("hr")
    HR("hr"),
    @XmlEnumValue("hr_HR")
    HR_HR("hr_HR"),
    @XmlEnumValue("hu")
    HU("hu"),
    @XmlEnumValue("hu_HU")
    HU_HU("hu_HU"),
    @XmlEnumValue("is")
    IS("is"),
    @XmlEnumValue("is_IS")
    IS_IS("is_IS"),
    @XmlEnumValue("it")
    IT("it"),
    @XmlEnumValue("it_CH")
    IT_CH("it_CH"),
    @XmlEnumValue("it_IT")
    IT_IT("it_IT"),
    @XmlEnumValue("it_IT_EURO")
    IT_IT_EURO("it_IT_EURO"),
    @XmlEnumValue("iw")
    IW("iw"),
    @XmlEnumValue("iw_IL")
    IW_IL("iw_IL"),
    @XmlEnumValue("ja")
    JA("ja"),
    @XmlEnumValue("ja_JP")
    JA_JP("ja_JP"),
    @XmlEnumValue("ko")
    KO("ko"),
    @XmlEnumValue("ko_KR")
    KO_KR("ko_KR"),
    @XmlEnumValue("lt")
    LT("lt"),
    @XmlEnumValue("lt_LT")
    LT_LT("lt_LT"),
    @XmlEnumValue("lv")
    LV("lv"),
    @XmlEnumValue("lv_LV")
    LV_LV("lv_LV"),
    @XmlEnumValue("mk")
    MK("mk"),
    @XmlEnumValue("mk_MK")
    MK_MK("mk_MK"),
    @XmlEnumValue("nl")
    NL("nl"),
    @XmlEnumValue("nl_BE")
    NL_BE("nl_BE"),
    @XmlEnumValue("nl_BE_EURO")
    NL_BE_EURO("nl_BE_EURO"),
    @XmlEnumValue("nl_NL")
    NL_NL("nl_NL"),
    @XmlEnumValue("nl_NL_EURO")
    NL_NL_EURO("nl_NL_EURO"),
    @XmlEnumValue("no")
    NO("no"),
    @XmlEnumValue("no_NO")
    NO_NO("no_NO"),
    @XmlEnumValue("no_NO_NY")
    NO_NO_NY("no_NO_NY"),
    @XmlEnumValue("pl")
    PL("pl"),
    @XmlEnumValue("pl_PL")
    PL_PL("pl_PL"),
    @XmlEnumValue("pt")
    PT("pt"),
    @XmlEnumValue("pt_BR")
    PT_BR("pt_BR"),
    @XmlEnumValue("pt_PT")
    PT_PT("pt_PT"),
    @XmlEnumValue("pt_PT_EURO")
    PT_PT_EURO("pt_PT_EURO"),
    @XmlEnumValue("ro")
    RO("ro"),
    @XmlEnumValue("ro_RO")
    RO_RO("ro_RO"),
    @XmlEnumValue("ru")
    RU("ru"),
    @XmlEnumValue("ru_RU")
    RU_RU("ru_RU"),
    @XmlEnumValue("sh")
    SH("sh"),
    @XmlEnumValue("sh_YU")
    SH_YU("sh_YU"),
    @XmlEnumValue("sk")
    SK("sk"),
    @XmlEnumValue("sk_SK")
    SK_SK("sk_SK"),
    @XmlEnumValue("sl")
    SL("sl"),
    @XmlEnumValue("sl_SI")
    SL_SI("sl_SI"),
    @XmlEnumValue("sq")
    SQ("sq"),
    @XmlEnumValue("sq_AL")
    SQ_AL("sq_AL"),
    @XmlEnumValue("sr")
    SR("sr"),
    @XmlEnumValue("sr_YU")
    SR_YU("sr_YU"),
    @XmlEnumValue("sv")
    SV("sv"),
    @XmlEnumValue("sv_SE")
    SV_SE("sv_SE"),
    @XmlEnumValue("th")
    TH("th"),
    @XmlEnumValue("th_TH")
    TH_TH("th_TH"),
    @XmlEnumValue("th_TH_TH")
    TH_TH_TH("th_TH_TH"),
    @XmlEnumValue("tr")
    TR("tr"),
    @XmlEnumValue("tr_TR")
    TR_TR("tr_TR"),
    @XmlEnumValue("uk")
    UK("uk"),
    @XmlEnumValue("uk_UA")
    UK_UA("uk_UA"),
    @XmlEnumValue("vi")
    VI("vi"),
    @XmlEnumValue("vi_VN")
    VI_VN("vi_VN"),
    @XmlEnumValue("zh")
    ZH("zh"),
    @XmlEnumValue("zh_CN")
    ZH_CN("zh_CN"),
    @XmlEnumValue("zh_HK")
    ZH_HK("zh_HK"),
    @XmlEnumValue("zh_TW")
    ZH_TW("zh_TW");
    private final String value;

    Locale(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Locale fromValue(String v) {
        for (Locale c: Locale.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
