//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 01:31:16 PM IST 
//


package com.sereneast.orchestramdm.keysight.mdmcustom.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sereneast.orchestramdm.keysight.mdmcustom.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Security_QNAME = new QName("http://schemas.xmlsoap.org/ws/2002/04/secext", "Security");
    private final static QName _CloseBranch_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "closeBranch");
    private final static QName _CloseBranchResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "closeBranch_Response");
    private final static QName _CloseVersion_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "closeVersion");
    private final static QName _CloseVersionResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "closeVersion_Response");
    private final static QName _CreateBranch_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "createBranch");
    private final static QName _CreateBranchResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "createBranch_Response");
    private final static QName _CreateVersion_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "createVersion");
    private final static QName _CreateVersionResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "createVersion_Response");
    private final static QName _LockBranch_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "lockBranch");
    private final static QName _LockBranchResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "lockBranch_Response");
    private final static QName _MergeBranch_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "mergeBranch");
    private final static QName _MergeBranchResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "mergeBranch_Response");
    private final static QName _UnlockBranch_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "unlockBranch");
    private final static QName _UnlockBranchResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "unlockBranch_Response");
    private final static QName _Validate_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "validate");
    private final static QName _ValidateResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "validate_Response");
    private final static QName _ValidateInstance_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "validateInstance");
    private final static QName _ValidateInstanceResponse_QNAME = new QName("urn:ebx-schemas:dataservices_1.0", "validateInstance_Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sereneast.orchestramdm.keysight.mdmcustom.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Session }
     * 
     */
    public Session createSession() {
        return new Session();
    }

    /**
     * Create an instance of {@link UDACatalog }
     * 
     */
    public UDACatalog createUDACatalog() {
        return new UDACatalog();
    }

    /**
     * Create an instance of {@link UDACatalog.Documentation }
     * 
     */
    public UDACatalog.Documentation createUDACatalogDocumentation() {
        return new UDACatalog.Documentation();
    }

    /**
     * Create an instance of {@link UDA }
     * 
     */
    public UDA createUDA() {
        return new UDA();
    }

    /**
     * Create an instance of {@link Session.InputParameters }
     * 
     */
    public Session.InputParameters createSessionInputParameters() {
        return new Session.InputParameters();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType }
     * 
     */
    public ValidateInstanceResponseType createValidateInstanceResponseType() {
        return new ValidateInstanceResponseType();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType.ValidationReport }
     * 
     */
    public ValidateInstanceResponseType.ValidationReport createValidateInstanceResponseTypeValidationReport() {
        return new ValidateInstanceResponseType.ValidationReport();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType.ValidationReport.Details }
     * 
     */
    public ValidateInstanceResponseType.ValidationReport.Details createValidateInstanceResponseTypeValidationReportDetails() {
        return new ValidateInstanceResponseType.ValidationReport.Details();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType.ValidationReport.Details.ReportItem }
     * 
     */
    public ValidateInstanceResponseType.ValidationReport.Details.ReportItem createValidateInstanceResponseTypeValidationReportDetailsReportItem() {
        return new ValidateInstanceResponseType.ValidationReport.Details.ReportItem();
    }

    /**
     * Create an instance of {@link ValidateInstanceRequestType }
     * 
     */
    public ValidateInstanceRequestType createValidateInstanceRequestType() {
        return new ValidateInstanceRequestType();
    }

    /**
     * Create an instance of {@link ValidateResponseType }
     * 
     */
    public ValidateResponseType createValidateResponseType() {
        return new ValidateResponseType();
    }

    /**
     * Create an instance of {@link LockBranchRequestType }
     * 
     */
    public LockBranchRequestType createLockBranchRequestType() {
        return new LockBranchRequestType();
    }

    /**
     * Create an instance of {@link CreateVersionRequestType }
     * 
     */
    public CreateVersionRequestType createCreateVersionRequestType() {
        return new CreateVersionRequestType();
    }

    /**
     * Create an instance of {@link CreateBranchRequestType }
     * 
     */
    public CreateBranchRequestType createCreateBranchRequestType() {
        return new CreateBranchRequestType();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link UsernameToken }
     * 
     */
    public UsernameToken createUsernameToken() {
        return new UsernameToken();
    }

    /**
     * Create an instance of {@link CloseBranchRequestType }
     * 
     */
    public CloseBranchRequestType createCloseBranchRequestType() {
        return new CloseBranchRequestType();
    }

    /**
     * Create an instance of {@link CloseBranchResponseType }
     * 
     */
    public CloseBranchResponseType createCloseBranchResponseType() {
        return new CloseBranchResponseType();
    }

    /**
     * Create an instance of {@link CloseVersionRequestType }
     * 
     */
    public CloseVersionRequestType createCloseVersionRequestType() {
        return new CloseVersionRequestType();
    }

    /**
     * Create an instance of {@link CloseVersionResponseType }
     * 
     */
    public CloseVersionResponseType createCloseVersionResponseType() {
        return new CloseVersionResponseType();
    }

    /**
     * Create an instance of {@link CreateBranchResponseType }
     * 
     */
    public CreateBranchResponseType createCreateBranchResponseType() {
        return new CreateBranchResponseType();
    }

    /**
     * Create an instance of {@link CreateVersionResponseType }
     * 
     */
    public CreateVersionResponseType createCreateVersionResponseType() {
        return new CreateVersionResponseType();
    }

    /**
     * Create an instance of {@link LockBranchResponseType }
     * 
     */
    public LockBranchResponseType createLockBranchResponseType() {
        return new LockBranchResponseType();
    }

    /**
     * Create an instance of {@link MergeBranchRequestType }
     * 
     */
    public MergeBranchRequestType createMergeBranchRequestType() {
        return new MergeBranchRequestType();
    }

    /**
     * Create an instance of {@link MergeBranchResponseType }
     * 
     */
    public MergeBranchResponseType createMergeBranchResponseType() {
        return new MergeBranchResponseType();
    }

    /**
     * Create an instance of {@link UnlockBranchRequestType }
     * 
     */
    public UnlockBranchRequestType createUnlockBranchRequestType() {
        return new UnlockBranchRequestType();
    }

    /**
     * Create an instance of {@link UnlockBranchResponseType }
     * 
     */
    public UnlockBranchResponseType createUnlockBranchResponseType() {
        return new UnlockBranchResponseType();
    }

    /**
     * Create an instance of {@link ValidateRequestType }
     * 
     */
    public ValidateRequestType createValidateRequestType() {
        return new ValidateRequestType();
    }

    /**
     * Create an instance of {@link StandardException }
     * 
     */
    public StandardException createStandardException() {
        return new StandardException();
    }

    /**
     * Create an instance of {@link UDACatalog.Documentation.LocalizedDocumentations }
     * 
     */
    public UDACatalog.Documentation.LocalizedDocumentations createUDACatalogDocumentationLocalizedDocumentations() {
        return new UDACatalog.Documentation.LocalizedDocumentations();
    }

    /**
     * Create an instance of {@link UDA.Value }
     * 
     */
    public UDA.Value createUDAValue() {
        return new UDA.Value();
    }

    /**
     * Create an instance of {@link Session.InputParameters.Parameter }
     * 
     */
    public Session.InputParameters.Parameter createSessionInputParametersParameter() {
        return new Session.InputParameters.Parameter();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType.ValidationReport.Details.ReportItem.UserMessage }
     * 
     */
    public ValidateInstanceResponseType.ValidationReport.Details.ReportItem.UserMessage createValidateInstanceResponseTypeValidationReportDetailsReportItemUserMessage() {
        return new ValidateInstanceResponseType.ValidationReport.Details.ReportItem.UserMessage();
    }

    /**
     * Create an instance of {@link ValidateInstanceResponseType.ValidationReport.Details.ReportItem.Subject }
     * 
     */
    public ValidateInstanceResponseType.ValidationReport.Details.ReportItem.Subject createValidateInstanceResponseTypeValidationReportDetailsReportItemSubject() {
        return new ValidateInstanceResponseType.ValidationReport.Details.ReportItem.Subject();
    }

    /**
     * Create an instance of {@link ValidateInstanceRequestType.Details }
     * 
     */
    public ValidateInstanceRequestType.Details createValidateInstanceRequestTypeDetails() {
        return new ValidateInstanceRequestType.Details();
    }

    /**
     * Create an instance of {@link ValidateResponseType.ValidationReport }
     * 
     */
    public ValidateResponseType.ValidationReport createValidateResponseTypeValidationReport() {
        return new ValidateResponseType.ValidationReport();
    }

    /**
     * Create an instance of {@link LockBranchRequestType.Message }
     * 
     */
    public LockBranchRequestType.Message createLockBranchRequestTypeMessage() {
        return new LockBranchRequestType.Message();
    }

    /**
     * Create an instance of {@link CreateVersionRequestType.Documentation }
     * 
     */
    public CreateVersionRequestType.Documentation createCreateVersionRequestTypeDocumentation() {
        return new CreateVersionRequestType.Documentation();
    }

    /**
     * Create an instance of {@link CreateBranchRequestType.Documentation }
     * 
     */
    public CreateBranchRequestType.Documentation createCreateBranchRequestTypeDocumentation() {
        return new CreateBranchRequestType.Documentation();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Security }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/ws/2002/04/secext", name = "Security")
    public JAXBElement<Security> createSecurity(Security value) {
        return new JAXBElement<Security>(_Security_QNAME, Security.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseBranchRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "closeBranch")
    public JAXBElement<CloseBranchRequestType> createCloseBranch(CloseBranchRequestType value) {
        return new JAXBElement<CloseBranchRequestType>(_CloseBranch_QNAME, CloseBranchRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseBranchResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "closeBranch_Response")
    public JAXBElement<CloseBranchResponseType> createCloseBranchResponse(CloseBranchResponseType value) {
        return new JAXBElement<CloseBranchResponseType>(_CloseBranchResponse_QNAME, CloseBranchResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseVersionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "closeVersion")
    public JAXBElement<CloseVersionRequestType> createCloseVersion(CloseVersionRequestType value) {
        return new JAXBElement<CloseVersionRequestType>(_CloseVersion_QNAME, CloseVersionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CloseVersionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "closeVersion_Response")
    public JAXBElement<CloseVersionResponseType> createCloseVersionResponse(CloseVersionResponseType value) {
        return new JAXBElement<CloseVersionResponseType>(_CloseVersionResponse_QNAME, CloseVersionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateBranchRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "createBranch")
    public JAXBElement<CreateBranchRequestType> createCreateBranch(CreateBranchRequestType value) {
        return new JAXBElement<CreateBranchRequestType>(_CreateBranch_QNAME, CreateBranchRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateBranchResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "createBranch_Response")
    public JAXBElement<CreateBranchResponseType> createCreateBranchResponse(CreateBranchResponseType value) {
        return new JAXBElement<CreateBranchResponseType>(_CreateBranchResponse_QNAME, CreateBranchResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateVersionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "createVersion")
    public JAXBElement<CreateVersionRequestType> createCreateVersion(CreateVersionRequestType value) {
        return new JAXBElement<CreateVersionRequestType>(_CreateVersion_QNAME, CreateVersionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateVersionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "createVersion_Response")
    public JAXBElement<CreateVersionResponseType> createCreateVersionResponse(CreateVersionResponseType value) {
        return new JAXBElement<CreateVersionResponseType>(_CreateVersionResponse_QNAME, CreateVersionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockBranchRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "lockBranch")
    public JAXBElement<LockBranchRequestType> createLockBranch(LockBranchRequestType value) {
        return new JAXBElement<LockBranchRequestType>(_LockBranch_QNAME, LockBranchRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockBranchResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "lockBranch_Response")
    public JAXBElement<LockBranchResponseType> createLockBranchResponse(LockBranchResponseType value) {
        return new JAXBElement<LockBranchResponseType>(_LockBranchResponse_QNAME, LockBranchResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MergeBranchRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "mergeBranch")
    public JAXBElement<MergeBranchRequestType> createMergeBranch(MergeBranchRequestType value) {
        return new JAXBElement<MergeBranchRequestType>(_MergeBranch_QNAME, MergeBranchRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MergeBranchResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "mergeBranch_Response")
    public JAXBElement<MergeBranchResponseType> createMergeBranchResponse(MergeBranchResponseType value) {
        return new JAXBElement<MergeBranchResponseType>(_MergeBranchResponse_QNAME, MergeBranchResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockBranchRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "unlockBranch")
    public JAXBElement<UnlockBranchRequestType> createUnlockBranch(UnlockBranchRequestType value) {
        return new JAXBElement<UnlockBranchRequestType>(_UnlockBranch_QNAME, UnlockBranchRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockBranchResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "unlockBranch_Response")
    public JAXBElement<UnlockBranchResponseType> createUnlockBranchResponse(UnlockBranchResponseType value) {
        return new JAXBElement<UnlockBranchResponseType>(_UnlockBranchResponse_QNAME, UnlockBranchResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "validate")
    public JAXBElement<ValidateRequestType> createValidate(ValidateRequestType value) {
        return new JAXBElement<ValidateRequestType>(_Validate_QNAME, ValidateRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "validate_Response")
    public JAXBElement<ValidateResponseType> createValidateResponse(ValidateResponseType value) {
        return new JAXBElement<ValidateResponseType>(_ValidateResponse_QNAME, ValidateResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateInstanceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "validateInstance")
    public JAXBElement<ValidateInstanceRequestType> createValidateInstance(ValidateInstanceRequestType value) {
        return new JAXBElement<ValidateInstanceRequestType>(_ValidateInstance_QNAME, ValidateInstanceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidateInstanceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:ebx-schemas:dataservices_1.0", name = "validateInstance_Response")
    public JAXBElement<ValidateInstanceResponseType> createValidateInstanceResponse(ValidateInstanceResponseType value) {
        return new JAXBElement<ValidateInstanceResponseType>(_ValidateInstanceResponse_QNAME, ValidateInstanceResponseType.class, null, value);
    }

}
