//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.19 at 01:31:16 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ebx-schemas:dataservices_1.0")
package com.sereneast.orchestramdm.keysight.mdmcustom.ws;
