package com.sereneast.orchestramdm.keysight.mdmcustom;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 GP2 [1060], at  2017/12/08 15:17:11 [IST].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Publication: Account].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		421 path constants.
	//		289 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Account
	{
		private static final Path _Account = _Root.add("Account");
		public static Path getPathInSchema()
		{
			return _Account;
		}
		public static final Path _MDMAccountId = Path.parse("./MDMAccountId");
		public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
		public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
		public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
		public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
		public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
		public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
		public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
		public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
		public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
		public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores_SurrogateField = Path.parse("./DaqaMetaData/fieldScores/surrogateField");
		public static final Path _DaqaMetaData_FieldScores_SurrogateScore = Path.parse("./DaqaMetaData/fieldScores/surrogateScore");
		public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
		public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
		public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
		public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
		public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
		public static final Path _DaqaMetaData_AutoCreated = Path.parse("./DaqaMetaData/AutoCreated");
		public static final Path _DaqaMetaData_UsedSurrogateFieldsMatching = Path.parse("./DaqaMetaData/usedSurrogateFieldsMatching");
		public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
		public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
		public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
		public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
		public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
		public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
		public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
		public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
		public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
		public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
		public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
		public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
		public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
		public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
		public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
		public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
		public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
		public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
		public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
		public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
		public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
		public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
		public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
		public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
		public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
		public static final Path _InternalAccountId = Path.parse("./InternalAccountId");
		public static final Path _AccountName = Path.parse("./AccountName");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _SystemId = Path.parse("./SystemId");
		public static final Path _RMTId = Path.parse("./RMTId");
		public static final Path _SystemName = Path.parse("./SystemName");
		public static final Path _CustomerType = Path.parse("./CustomerType");
		public static final Path _RegistryId = Path.parse("./RegistryId");
		public static final Path _CustomerCategory = Path.parse("./CustomerCategory");
		public static final Path _Reference = Path.parse("./Reference");
		public static final Path _GroupingId = Path.parse("./GroupingId");
		public static final Path _GroupingDescription = Path.parse("./GroupingDescription");
		public static final Path _ISGClassification = Path.parse("./ISGClassification");
		public static final Path _NamePronunciation = Path.parse("./NamePronunciation");
		public static final Path _TaxpayerId = Path.parse("./TaxpayerId");
		public static final Path _TaxRegistrationNumber = Path.parse("./TaxRegistrationNumber");
		public static final Path _Region = Path.parse("./Region");
		public static final Path _Classification = Path.parse("./Classification");
		public static final Path _AccountType = Path.parse("./AccountType");
		public static final Path _SalesChannel = Path.parse("./SalesChannel");
		public static final Path _NLSLanguageCode = Path.parse("./NLSLanguageCode");
		public static final Path _NameLocalLanguage = Path.parse("./NameLocalLanguage");
		public static final Path _CustomerScreening = Path.parse("./CustomerScreening");
		public static final Path _ParentParty = Path.parse("./ParentParty");
		public static final Path _EmgLastTrans = Path.parse("./EmgLastTrans");
		public static final Path _ProfileClass = Path.parse("./ProfileClass");
		public static final Path _Country = Path.parse("./Country");
		public static final Path _PaymentReceiptMethod = Path.parse("./PaymentReceiptMethod");
		public static final Path _PrimaryPayment = Path.parse("./PrimaryPayment");
		public static final Path _PaymentStartDate = Path.parse("./PaymentStartDate");
		public static final Path _PaymentEndDate = Path.parse("./PaymentEndDate");
		public static final Path _Notes = Path.parse("./Notes");
		public static final Path _AssignedTo = Path.parse("./AssignedTo");
		public static final Path _Published = Path.parse("./Published");
		public static final Path _LastPublished = Path.parse("./LastPublished");
		public static final Path _BatchCode = Path.parse("./BatchCode");
		public static final Path _Locale = Path.parse("./Locale");
		public static final Path _RelatedAddress = Path.parse("./RelatedAddress");
		public static final Path _MergedTargetRecord = Path.parse("./MergedTargetRecord");
	} 

	// Table type path
	public final class _Address
	{
		private static final Path _AddressTable = _Root.add("Address");
		public static Path getPathInSchema()
		{
			return _AddressTable;
		}
		public static final Path _MDMAddressId = Path.parse("./MDMAddressId");
		public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
		public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
		public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
		public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
		public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
		public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
		public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
		public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
		public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
		public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores_SurrogateField = Path.parse("./DaqaMetaData/fieldScores/surrogateField");
		public static final Path _DaqaMetaData_FieldScores_SurrogateScore = Path.parse("./DaqaMetaData/fieldScores/surrogateScore");
		public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
		public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
		public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
		public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
		public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
		public static final Path _DaqaMetaData_AutoCreated = Path.parse("./DaqaMetaData/AutoCreated");
		public static final Path _DaqaMetaData_UsedSurrogateFieldsMatching = Path.parse("./DaqaMetaData/usedSurrogateFieldsMatching");
		public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
		public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
		public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
		public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
		public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
		public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
		public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
		public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
		public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
		public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
		public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
		public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
		public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
		public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
		public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
		public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
		public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
		public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
		public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
		public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
		public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
		public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
		public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
		public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
		public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
		public static final Path _MDMAccountId = Path.parse("./MDMAccountId");
		public static final Path _AccountName = Path.parse("./AccountName");
		public static final Path _AccountNameLocalLanguage = Path.parse("./AccountNameLocalLanguage");
		public static final Path _InternalAccountId = Path.parse("./InternalAccountId");
		public static final Path _InternalAddressId = Path.parse("./InternalAddressId");
		public static final Path _ParentSystemId = Path.parse("./ParentSystemId");
		public static final Path _SystemId = Path.parse("./SystemId");
		public static final Path _RMTId = Path.parse("./RMTId");
		public static final Path _SystemName = Path.parse("./SystemName");
		public static final Path _AddressLine1 = Path.parse("./AddressLine1");
		public static final Path _AddressLine2 = Path.parse("./AddressLine2");
		public static final Path _AddressLine3 = Path.parse("./AddressLine3");
		public static final Path _AddressLine4 = Path.parse("./AddressLine4");
		public static final Path _Address = Path.parse("./Address");
		public static final Path _City = Path.parse("./City");
		public static final Path _County = Path.parse("./County");
		public static final Path _AddressState = Path.parse("./AddressState");
		public static final Path _Province = Path.parse("./Province");
		public static final Path _PostalCode = Path.parse("./PostalCode");
		public static final Path _Country = Path.parse("./Country");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _IdentifyingAddress = Path.parse("./IdentifyingAddress");
		public static final Path _Reference = Path.parse("./Reference");
		public static final Path _OperatingUnit = Path.parse("./OperatingUnit");
		public static final Path _RPLCheck = Path.parse("./RPLCheck");
		public static final Path _NLSLanguage = Path.parse("./NLSLanguage");
		public static final Path _AddressLine1LocalLanguage = Path.parse("./AddressLine1LocalLanguage");
		public static final Path _AddressLine2LocalLanguage = Path.parse("./AddressLine2LocalLanguage");
		public static final Path _AddressLine3LocalLanguage = Path.parse("./AddressLine3LocalLanguage");
		public static final Path _AddressLine4LocalLanguage = Path.parse("./AddressLine4LocalLanguage");
		public static final Path _CityLocalLanguage = Path.parse("./CityLocalLanguage");
		public static final Path _StateLocalLanguage = Path.parse("./StateLocalLanguage");
		public static final Path _PostalLocalLanguage = Path.parse("./PostalLocalLanguage");
		public static final Path _ProvinceLocalLanguage = Path.parse("./ProvinceLocalLanguage");
		public static final Path _CountyLocalLanguage = Path.parse("./CountyLocalLanguage");
		public static final Path _CountryLocalLanguage = Path.parse("./CountryLocalLanguage");
		public static final Path _SendAcknowledgement = Path.parse("./SendAcknowledgement");
		public static final Path _InvoiceCopies = Path.parse("./InvoiceCopies");
		public static final Path _ContextValue = Path.parse("./ContextValue");
		public static final Path _TaxablePerson = Path.parse("./TaxablePerson");
		public static final Path _IndustryClassification = Path.parse("./IndustryClassification");
		public static final Path _TaxCertificateDate = Path.parse("./TaxCertificateDate");
		public static final Path _BusinessNumber = Path.parse("./BusinessNumber");
		public static final Path _IndustrySubclassification = Path.parse("./IndustrySubclassification");
		public static final Path _AddressSiteCategory = Path.parse("./AddressSiteCategory");
		public static final Path _ATS = Path.parse("./ATS");
		public static final Path _BillToLocation = Path.parse("./BillToLocation");
		public static final Path _RevenueRecognition = Path.parse("./RevenueRecognition");
		public static final Path _OrgSegment = Path.parse("./OrgSegment");
		public static final Path _SubSegmet = Path.parse("./SubSegmet");
		public static final Path _DemandClass = Path.parse("./DemandClass");
		public static final Path _TaxRegistrationActive = Path.parse("./TaxRegistrationActive");
		public static final Path _TaxRegimeCode = Path.parse("./TaxRegimeCode");
		public static final Path _Tax = Path.parse("./Tax");
		public static final Path _TaxRegistrationNumber = Path.parse("./TaxRegistrationNumber");
		public static final Path _Source = Path.parse("./Source");
		public static final Path _DefaultTaxRegistration = Path.parse("./DefaultTaxRegistration");
		public static final Path _TaxEffectiveFrom = Path.parse("./TaxEffectiveFrom");
		public static final Path _TaxEffectiveTo = Path.parse("./TaxEffectiveTo");
		public static final Path _InscriptionType = Path.parse("./InscriptionType");
		public static final Path _InsciptionNumber = Path.parse("./InsciptionNumber");
		public static final Path _InscriptionBranch = Path.parse("./InscriptionBranch");
		public static final Path _InscriptionDigit = Path.parse("./InscriptionDigit");
		public static final Path _StateInscription = Path.parse("./StateInscription");
		public static final Path _MunicipalInscription = Path.parse("./MunicipalInscription");
		public static final Path _ContributorClass = Path.parse("./ContributorClass");
		public static final Path _UseCustSiteProfile = Path.parse("./UseCustSiteProfile");
		public static final Path _SUFRAMAInscriptionNumber = Path.parse("./SUFRAMAInscriptionNumber");
		public static final Path _AssignedTo = Path.parse("./AssignedTo");
		public static final Path _Published = Path.parse("./Published");
		public static final Path _LastPublished = Path.parse("./LastPublished");
		public static final Path _BatchCode = Path.parse("./BatchCode");
		public static final Path _SpecialHandling = Path.parse("./SpecialHandling");
		public static final Path _Locale = Path.parse("./Locale");
		public static final Path _RelatedBusinessPurpose = Path.parse("./RelatedBusinessPurpose");
		public static final Path _MergedTargetRecord = Path.parse("./MergedTargetRecord");
	} 

	// Table type path
	public final class _BusinessPurpose
	{
		private static final Path _BusinessPurposeTable = _Root.add("BusinessPurpose");
		public static Path getPathInSchema()
		{
			return _BusinessPurposeTable;
		}
		public static final Path _MDMPurposeId = Path.parse("./MDMPurposeId");
		public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
		public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
		public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
		public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
		public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
		public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
		public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
		public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
		public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
		public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores_SurrogateField = Path.parse("./DaqaMetaData/fieldScores/surrogateField");
		public static final Path _DaqaMetaData_FieldScores_SurrogateScore = Path.parse("./DaqaMetaData/fieldScores/surrogateScore");
		public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
		public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
		public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
		public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
		public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
		public static final Path _DaqaMetaData_AutoCreated = Path.parse("./DaqaMetaData/AutoCreated");
		public static final Path _DaqaMetaData_UsedSurrogateFieldsMatching = Path.parse("./DaqaMetaData/usedSurrogateFieldsMatching");
		public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
		public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
		public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
		public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
		public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
		public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
		public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
		public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
		public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
		public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
		public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
		public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
		public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
		public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
		public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
		public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
		public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
		public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
		public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
		public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
		public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
		public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
		public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
		public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
		public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
		public static final Path _MDMAddressId = Path.parse("./MDMAddressId");
		public static final Path _SystemId = Path.parse("./SystemId");
		public static final Path _SystemName = Path.parse("./SystemName");
		public static final Path _Primary = Path.parse("./Primary");
		public static final Path _BusinessPurpose = Path.parse("./BusinessPurpose");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _Location = Path.parse("./Location");
		public static final Path _BatchCode = Path.parse("./BatchCode");
		public static final Path _OperatingUnit = Path.parse("./OperatingUnit");
	} 

	// Table type path
	public final class _RegimeCode
	{
		private static final Path _RegimeCode = _Root.add("RegimeCode");
		public static Path getPathInSchema()
		{
			return _RegimeCode;
		}
		public static final Path _CountryCode = Path.parse("./CountryCode");
		public static final Path _TaxRegimeCode = Path.parse("./TaxRegimeCode");
		public static final Path _TerritoryShortName = Path.parse("./TerritoryShortName");
	} 

	// Table type path
	public final class _Province
	{
		private static final Path _ProvinceTable = _Root.add("Province");
		public static Path getPathInSchema()
		{
			return _ProvinceTable;
		}
		public static final Path _CountryCode = Path.parse("./CountryCode");
		public static final Path _ProvinceCode = Path.parse("./ProvinceCode");
		public static final Path _Province = Path.parse("./Province");
	} 

	// Table type path
	public final class _State
	{
		private static final Path _StateTable = _Root.add("State");
		public static Path getPathInSchema()
		{
			return _StateTable;
		}
		public static final Path _StateCode = Path.parse("./StateCode");
		public static final Path _CountryCode = Path.parse("./CountryCode");
		public static final Path _State = Path.parse("./State");
	} 

	// Table type path
	public final class _CountryReferenceFields
	{
		private static final Path _CountryReferenceFields = _Root.add("CountryReferenceFields");
		public static Path getPathInSchema()
		{
			return _CountryReferenceFields;
		}
		public static final Path _Id = Path.parse("./Id");
		public static final Path _CountryCode = Path.parse("./CountryCode");
		public static final Path _Country = Path.parse("./Country");
		public static final Path _OperatingUnit = Path.parse("./OperatingUnit");
		public static final Path _Region = Path.parse("./Region");
		public static final Path _ProfileClass = Path.parse("./ProfileClass");
		public static final Path _RegimeCode = Path.parse("./RegimeCode");
	} 

	// Table type path
	public final class _AssignTo
	{
		private static final Path _AssignTo = _Root.add("AssignTo");
		public static Path getPathInSchema()
		{
			return _AssignTo;
		}
		public static final Path _Login = Path.parse("./login");
		public static final Path _FirstName = Path.parse("./firstName");
		public static final Path _LastName = Path.parse("./lastName");
		public static final Path _Email = Path.parse("./email");
	} 

	// Table type path
	public final class _ProfileClass
	{
		private static final Path _ProfileClassTable = _Root.add("ProfileClass");
		public static Path getPathInSchema()
		{
			return _ProfileClassTable;
		}
		public static final Path _ProfileClass = Path.parse("./ProfileClass");
		public static final Path _Label = Path.parse("./label");
		public static final Path _Display = Path.parse("./Display");
	} 

	// Table type path
	public final class _OrgSubSegment
	{
		private static final Path _OrgSubSegmentTable = _Root.add("OrgSubSegment");
		public static Path getPathInSchema()
		{
			return _OrgSubSegmentTable;
		}
		public static final Path _OrgSubSegment = Path.parse("./OrgSubSegment");
		public static final Path _OrgSegment = Path.parse("./OrgSegment");
	} 

	// Table type path
	public final class _OperatingUnit
	{
		private static final Path _OperatingUnitTable = _Root.add("OperatingUnit");
		public static Path getPathInSchema()
		{
			return _OperatingUnitTable;
		}
		public static final Path _OperatingUnit = Path.parse("./OperatingUnit");
		public static final Path _Label = Path.parse("./label");
		public static final Path _Display = Path.parse("./Display");
	} 
	// ===============================================

}
