package com.sereneast.orchestramdm.keysight.mdmcustom;

import com.orchestranetworks.schema.*;
/**
 * Generated by EBX5 5.8.1 GP2 [1060], at  2017/09/25 18:07:46 [PDT].
 * WARNING: Any manual changes to this class may be overwritten by generation process.
 * DO NOT MODIFY THIS CLASS.
 * 
 * This interface defines constants related to schema [Module: mdmcustomapp, path: /WEB-INF/ebx/schemas/mdmcustomapp.xsd].
 * 
 * Root paths in this interface: 
 * 	'/root'   relativeToRoot: false
 * 
 */
public interface Paths
{
	// ===============================================
	// Constants for nodes under '/root'.
	// Prefix:  ''.
	// Statistics:
	//		240 path constants.
	//		205 leaf nodes.
	public static final Path _Root = Path.parse("/root");

	// Table type path
	public final class _Account
	{
		private static final Path _Account = _Root.add("Account");
		public static Path getPathInSchema()
		{
			return _Account;
		}
		public static final Path _MDMAccountId = Path.parse("./MDMAccountId");
		public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
		public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
		public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
		public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
		public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
		public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
		public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
		public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
		public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
		public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores_SurrogateField = Path.parse("./DaqaMetaData/fieldScores/surrogateField");
		public static final Path _DaqaMetaData_FieldScores_SurrogateScore = Path.parse("./DaqaMetaData/fieldScores/surrogateScore");
		public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
		public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
		public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
		public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
		public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
		public static final Path _DaqaMetaData_AutoCreated = Path.parse("./DaqaMetaData/AutoCreated");
		public static final Path _DaqaMetaData_UsedSurrogateFieldsMatching = Path.parse("./DaqaMetaData/usedSurrogateFieldsMatching");
		public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
		public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
		public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
		public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
		public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
		public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
		public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
		public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
		public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
		public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
		public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
		public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
		public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
		public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
		public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
		public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
		public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
		public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
		public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
		public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
		public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
		public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
		public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
		public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
		public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
		public static final Path _AccountNumber = Path.parse("./AccountNumber");
		public static final Path _AccountName = Path.parse("./AccountName");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _SystemId = Path.parse("./SystemId");
		public static final Path _SystemName = Path.parse("./SystemName");
		public static final Path _CustomerType = Path.parse("./CustomerType");
		public static final Path _RegistryId = Path.parse("./RegistryId");
		public static final Path _Alias = Path.parse("./Alias");
		public static final Path _NamePronunciation = Path.parse("./NamePronunciation");
		public static final Path _TaxpayerId = Path.parse("./TaxpayerId");
		public static final Path _TaxRegistrationNumber = Path.parse("./TaxRegistrationNumber");
		public static final Path _CustomerCategory = Path.parse("./CustomerCategory");
		public static final Path _AccountDescription = Path.parse("./AccountDescription");
		public static final Path _Region = Path.parse("./Region");
		public static final Path _Classification = Path.parse("./Classification");
		public static final Path _AccountType = Path.parse("./AccountType");
		public static final Path _SalesChannel = Path.parse("./SalesChannel");
		public static final Path _Reference = Path.parse("./Reference");
		public static final Path _NLSLanguageCode = Path.parse("./NLSLanguageCode");
		public static final Path _NameLocalLanguage = Path.parse("./NameLocalLanguage");
		public static final Path _CustomerScreening = Path.parse("./CustomerScreening");
		public static final Path _LastCreditReviewDate = Path.parse("./LastCreditReviewDate");
		public static final Path _NextCreditReviewDate = Path.parse("./NextCreditReviewDate");
		public static final Path _CreditReviewCycle = Path.parse("./CreditReviewCycle");
		public static final Path _ParentParty = Path.parse("./ParentParty");
		public static final Path _EmgLastTrans = Path.parse("./EmgLastTrans");
		public static final Path _GroupingDescription = Path.parse("./GroupingDescription");
		public static final Path _GroupingId = Path.parse("./GroupingId");
		public static final Path _IXIAClassification = Path.parse("./IXIAClassification");
		public static final Path _ProfileClass = Path.parse("./ProfileClass");
		public static final Path _RelatedAddress = Path.parse("./RelatedAddress");
		public static final Path _MergedTargetRecord = Path.parse("./MergedTargetRecord");
	} 

	// Table type path
	public final class _Address
	{
		private static final Path _Address = _Root.add("Address");
		public static Path getPathInSchema()
		{
			return _Address;
		}
		public static final Path _MDMAddressId = Path.parse("./MDMAddressId");
		public static final Path _MDMAccountId = Path.parse("./MDMAccountId");
		public static final Path _DaqaMetaData = Path.parse("./DaqaMetaData");
		public static final Path _DaqaMetaData_State = Path.parse("./DaqaMetaData/State");
		public static final Path _DaqaMetaData_ClusterId = Path.parse("./DaqaMetaData/ClusterId");
		public static final Path _DaqaMetaData_Score = Path.parse("./DaqaMetaData/Score");
		public static final Path _DaqaMetaData_ScoreFirstMatching = Path.parse("./DaqaMetaData/ScoreFirstMatching");
		public static final Path _DaqaMetaData_ScoreSecondMatching = Path.parse("./DaqaMetaData/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores = Path.parse("./DaqaMetaData/fieldScores");
		public static final Path _DaqaMetaData_FieldScores_Field = Path.parse("./DaqaMetaData/fieldScores/Field");
		public static final Path _DaqaMetaData_FieldScores_Score = Path.parse("./DaqaMetaData/fieldScores/Score");
		public static final Path _DaqaMetaData_FieldScores_ScoreFirstMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreFirstMatching");
		public static final Path _DaqaMetaData_FieldScores_ScoreSecondMatching = Path.parse("./DaqaMetaData/fieldScores/ScoreSecondMatching");
		public static final Path _DaqaMetaData_FieldScores_SurrogateField = Path.parse("./DaqaMetaData/fieldScores/surrogateField");
		public static final Path _DaqaMetaData_FieldScores_SurrogateScore = Path.parse("./DaqaMetaData/fieldScores/surrogateScore");
		public static final Path _DaqaMetaData_SimpleMatchingScore = Path.parse("./DaqaMetaData/simpleMatchingScore");
		public static final Path _DaqaMetaData_TargetRecord = Path.parse("./DaqaMetaData/TargetRecord");
		public static final Path _DaqaMetaData_MergeOrigin = Path.parse("./DaqaMetaData/MergeOrigin");
		public static final Path _DaqaMetaData_Timestamp = Path.parse("./DaqaMetaData/Timestamp");
		public static final Path _DaqaMetaData_WasGolden = Path.parse("./DaqaMetaData/WasGolden");
		public static final Path _DaqaMetaData_AutoCreated = Path.parse("./DaqaMetaData/AutoCreated");
		public static final Path _DaqaMetaData_UsedSurrogateFieldsMatching = Path.parse("./DaqaMetaData/usedSurrogateFieldsMatching");
		public static final Path _DaqaMetaData_ListOfNotSuspects = Path.parse("./DaqaMetaData/listOfNotSuspects");
		public static final Path _DaqaMetaData_ListOfNotSuspects_NotSuspectWith = Path.parse("./DaqaMetaData/listOfNotSuspects/NotSuspectWith");
		public static final Path _DaqaMetaData_ListOfNotSuspects_Score = Path.parse("./DaqaMetaData/listOfNotSuspects/Score");
		public static final Path _DaqaMetaData_GroupAtOnce = Path.parse("./DaqaMetaData/groupAtOnce");
		public static final Path _DaqaMetaData_GroupAtOnce_Grouped = Path.parse("./DaqaMetaData/groupAtOnce/grouped");
		public static final Path _DaqaMetaData_GroupAtOnce_ClusterSize = Path.parse("./DaqaMetaData/groupAtOnce/clusterSize");
		public static final Path _DaqaMetaData_Workflow = Path.parse("./DaqaMetaData/workflow");
		public static final Path _DaqaMetaData_Workflow_Uuid = Path.parse("./DaqaMetaData/workflow/Uuid");
		public static final Path _DaqaMetaData_Workflow_Name = Path.parse("./DaqaMetaData/workflow/Name");
		public static final Path _DaqaMetaData_Workflow_Timestamp = Path.parse("./DaqaMetaData/workflow/Timestamp");
		public static final Path _DaqaMetaData_Workflow_User = Path.parse("./DaqaMetaData/workflow/User");
		public static final Path _DaqaMetaData_ProcessPolicyCode = Path.parse("./DaqaMetaData/ProcessPolicyCode");
		public static final Path _DaqaMetaData_MatchingPolicyCode = Path.parse("./DaqaMetaData/MatchingPolicyCode");
		public static final Path _DaqaMetaData_SurvivorshipPolicyCode = Path.parse("./DaqaMetaData/SurvivorshipPolicyCode");
		public static final Path _DaqaMetaData_OperationCode = Path.parse("./DaqaMetaData/OperationCode");
		public static final Path _DaqaMetaData_DateOfLastOperationCode = Path.parse("./DaqaMetaData/DateOfLastOperationCode");
		public static final Path _DaqaMetaData_BatchOperationCode = Path.parse("./DaqaMetaData/BatchOperationCode");
		public static final Path _DaqaMetaData_CleansingMetadata = Path.parse("./DaqaMetaData/CleansingMetadata");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingState = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingState");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingProcedureCode = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingProcedureCode");
		public static final Path _DaqaMetaData_CleansingMetadata_CleansingOperation = Path.parse("./DaqaMetaData/CleansingMetadata/CleansingOperation");
		public static final Path _DaqaMetaData_CleansingMetadata_ExecutionDate = Path.parse("./DaqaMetaData/CleansingMetadata/ExecutionDate");
		public static final Path _DaqaMetaData_CleansingMetadata_User = Path.parse("./DaqaMetaData/CleansingMetadata/User");
		public static final Path _DaqaMetaData_CleansingMetadata_Field = Path.parse("./DaqaMetaData/CleansingMetadata/Field");
		public static final Path _DaqaMetaData_CleansingMetadata_QualityDefect = Path.parse("./DaqaMetaData/CleansingMetadata/QualityDefect");
		public static final Path _DaqaMetaData_FieldMergedLogging = Path.parse("./DaqaMetaData/fieldMergedLogging");
		public static final Path _DaqaMetaData_FieldMergedLogging_DateFieldMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/dateFieldMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedLogicalName = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedLogicalName");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldMergedValue = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldMergedValue");
		public static final Path _DaqaMetaData_FieldMergedLogging_FieldTargetValueBeforeMerged = Path.parse("./DaqaMetaData/fieldMergedLogging/fieldTargetValueBeforeMerged");
		public static final Path _DaqaMetaData_FieldMergedLogging_SurvivorshipFunctionCode = Path.parse("./DaqaMetaData/fieldMergedLogging/survivorshipFunctionCode");
		public static final Path _DaqaMetaData_FieldMergedLogging_PrimaryKeyMergedRecord = Path.parse("./DaqaMetaData/fieldMergedLogging/primaryKeyMergedRecord");
		public static final Path _SystemId = Path.parse("./SystemId");
		public static final Path _SystemName = Path.parse("./SystemName");
		public static final Path _SiteId = Path.parse("./SiteId");
		public static final Path _SiteNumber = Path.parse("./SiteNumber");
		public static final Path _SiteName = Path.parse("./SiteName");
		public static final Path _KeysightSFAAddressId = Path.parse("./KeysightSFAAddressId");
		public static final Path _AddressLine1 = Path.parse("./AddressLine1");
		public static final Path _AddressLine2 = Path.parse("./AddressLine2");
		public static final Path _AddressLine3 = Path.parse("./AddressLine3");
		public static final Path _AddressLine4 = Path.parse("./AddressLine4");
		public static final Path __Address = Path.parse("./Address");
		public static final Path _FullAddress = Path.parse("./FullAddress");
		public static final Path _City = Path.parse("./City");
		public static final Path _County = Path.parse("./County");
		public static final Path _AddressState = Path.parse("./AddressState");
		public static final Path _Province = Path.parse("./Province");
		public static final Path _PostalCode = Path.parse("./PostalCode");
		public static final Path _CalcPostalCOde = Path.parse("./CalcPostalCOde");
		public static final Path _Country = Path.parse("./Country");
		public static final Path _Addressee = Path.parse("./Addressee");
		public static final Path _Status = Path.parse("./Status");
		public static final Path _IdentifyingAddress = Path.parse("./IdentifyingAddress");
		public static final Path _Reference = Path.parse("./Reference");
		public static final Path _Translation = Path.parse("./Translation");
		public static final Path _OperatingUnit = Path.parse("./OperatingUnit");
		public static final Path _RPLCheck = Path.parse("./RPLCheck");
		public static final Path _NLSLanguage = Path.parse("./NLSLanguage");
		public static final Path _AddressLine1LocalLanguage = Path.parse("./AddressLine1LocalLanguage");
		public static final Path _AddressLine2LocalLanguage = Path.parse("./AddressLine2LocalLanguage");
		public static final Path _AddressLine3LocalLanguage = Path.parse("./AddressLine3LocalLanguage");
		public static final Path _AddressLine4LocalLanguage = Path.parse("./AddressLine4LocalLanguage");
		public static final Path _CityLocalLanguage = Path.parse("./CityLocalLanguage");
		public static final Path _StateLocalLanguage = Path.parse("./StateLocalLanguage");
		public static final Path _PostalLocalLanguage = Path.parse("./PostalLocalLanguage");
		public static final Path _ProvinceLocalLanguage = Path.parse("./ProvinceLocalLanguage");
		public static final Path _CountyLocalLanguage = Path.parse("./CountyLocalLanguage");
		public static final Path _CountryLocalLanguage = Path.parse("./CountryLocalLanguage");
		public static final Path _SendAcknowledgement = Path.parse("./SendAcknowledgement");
		public static final Path _InvoiceCopies = Path.parse("./InvoiceCopies");
		public static final Path _AccountSiteType = Path.parse("./AccountSiteType");
		public static final Path _ContextValue = Path.parse("./ContextValue");
		public static final Path _TaxablePerson = Path.parse("./TaxablePerson");
		public static final Path _IndustryClassification = Path.parse("./IndustryClassification");
		public static final Path _TaxCertificateDate = Path.parse("./TaxCertificateDate");
		public static final Path _BusinessNumber = Path.parse("./BusinessNumber");
		public static final Path _IndustrySubclassification = Path.parse("./IndustrySubclassification");
		public static final Path _AddressSiteCategory = Path.parse("./AddressSiteCategory");
		public static final Path _ATS = Path.parse("./ATS");
		public static final Path _BusinessPurpose = Path.parse("./BusinessPurpose");
		public static final Path _Location = Path.parse("./Location");
		public static final Path _BillToLocation = Path.parse("./BillToLocation");
		public static final Path _PrimaryPurpose = Path.parse("./PrimaryPurpose");
		public static final Path _RevenueRecognition = Path.parse("./RevenueRecognition");
		public static final Path _OrgSegment = Path.parse("./OrgSegment");
		public static final Path _SubSegment = Path.parse("./SubSegment");
		public static final Path _AccountClass = Path.parse("./AccountClass");
		public static final Path _Receivable = Path.parse("./Receivable");
		public static final Path _Revenue = Path.parse("./Revenue");
		public static final Path _PaymentTerms = Path.parse("./PaymentTerms");
		public static final Path _SalesPerson = Path.parse("./SalesPerson");
		public static final Path _OrderType = Path.parse("./OrderType");
		public static final Path _PriceList = Path.parse("./PriceList");
		public static final Path _DemandClass = Path.parse("./DemandClass");
		public static final Path _ReceiptMethods = Path.parse("./ReceiptMethods");
		public static final Path _PrimaryPayment = Path.parse("./PrimaryPayment");
		public static final Path _StartDate = Path.parse("./StartDate");
		public static final Path _EndDate = Path.parse("./EndDate");
		public static final Path _DefaultReportingCountryName = Path.parse("./DefaultReportingCountryName");
		public static final Path _DefaultReportingRegistrationNumber = Path.parse("./DefaultReportingRegistrationNumber");
		public static final Path _TaxRegistrationActive = Path.parse("./TaxRegistrationActive");
		public static final Path _RegimeCode = Path.parse("./RegimeCode");
		public static final Path _Tax = Path.parse("./Tax");
		public static final Path _TaxJurisdictionCode = Path.parse("./TaxJurisdictionCode");
		public static final Path _TaxRegistrationNumber = Path.parse("./TaxRegistrationNumber");
		public static final Path _Source = Path.parse("./Source");
		public static final Path _DefaultTaxRegistration = Path.parse("./DefaultTaxRegistration");
		public static final Path _EfectiveFrom = Path.parse("./EfectiveFrom");
		public static final Path _EffectiveTo = Path.parse("./EffectiveTo");
		public static final Path _RoundingRule = Path.parse("./RoundingRule");
		public static final Path _MergedTargetRecord = Path.parse("./MergedTargetRecord");
	} 
	// ===============================================

}
